# Generated by Django 5.1.6 on 2025-03-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50)),
                ('lead_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.researchproject')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_research_requests', to='core.hospital')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.researchproject')),
                ('to_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_research_requests', to='core.hospital')),
            ],
        ),
    ]
