# Generated by Django 5.1.6 on 2025-03-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_researchproject_researchcollaboration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='lead_hospital',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='status',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.hospital'),
        ),
    ]
