# Generated by Django 5.1.6 on 2025-03-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_ambulancebooking_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='ambulancebooking',
            name='pickup_longitude',
        ),
    ]
