# Generated by Django 5.1.6 on 2025-03-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_ambulancebooking_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancebooking',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulancebooking',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
