# Generated by Django 5.1.6 on 2025-03-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_ambulancebooking_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='specialization',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.specialization'),
        ),
    ]
