# Generated by Django 5.1.6 on 2025-03-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_hospital_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('leave', 'On Leave'), ('rounds', 'On Rounds'), ('busy', 'Busy')], default='active', max_length=20),
        ),
    ]
