# Generated by Django 5.1.6 on 2025-03-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_availableday_doctor_end_time_doctor_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='AvailableDay',
        ),
    ]
