# Generated by Django 5.1.6 on 2025-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_doctor_available_days_doctor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
