# Generated by Django 5.1.6 on 2025-03-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_doctor_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.TextField(default='Monday'),
        ),
    ]
