# Generated by Django 5.2 on 2025-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_doctor_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
