# Generated by Django 5.2 on 2025-04-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_hospital_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
